import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Sidebar from "@/components/layout/Sidebar";
import ActiveUser from "@/components/feed/ActiveUser";
import Header from "@/components/layout/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Header />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
          {/* Sidebar - takes 4/12 of the space */}
          <div className="col-span-1 md:col-span-5">
            <Sidebar />
          </div>

          {/* Main content - takes 5/12 of the space */}
          <div className="col-span-1 md:col-span-5">{children}</div>

          {/* Active users - takes 2/12 of the space (smaller) */}
          <div className="col-span-1 md:col-span-2">
            <ActiveUser />
          </div>
        </div>
      </body>
    </html>
  );
}
